config/routes.rb
Fetchit::Application.routes.draw do
  resources :links, :only => [:index, :create, :show] do
    get 'page/:page', :action => :index, :on => :collection
    get 'raw', :action => :raw
  end
  
  root :to => 'links#index'
  
  mount Resque::Server, :at => '/resque'
end

app/models/link.rb
class Link < ActiveRecord::Base
  require 'digest/sha2'
  validates_presence_of :url, :on => :create, :message => "can't be blank"
  
  before_save :gen_key
  before_save :clean_url
  belongs_to :user_agent, :class_name => "UserAgent", :foreign_key => "user_agent_id"
  
  private
  
  def clean_url
    uri = URI.parse(self.url)
    unless uri.scheme == 'http' or uri.scheme == 'https'
      if uri.host.nil?
        self.url = "http://" + uri.path
      else
        self.url = "http://" + uri.host
      end
      if uri.path.empty?
        self.url = self.url + "/"
      end
    end
  end
  
  def gen_key
    if self.hashkey.nil?
      hasher = Digest::SHA2.new
      self.hashkey = hasher.update(self.url).to_s
    end
  end
end

app/models/user_agent.rb
class UserAgent < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/link_controller.rb
class LinkController < ApplicationController
  def index
    @links = Link.order('updated_at DESC').page
  end

  def show
    @link = Link.find(params[:id])
    @headers = @link.processed? ? YAML.load(@link.headers) : {}
  end

  def create
    unless RateLimiter.limit(request.remote_ip)
      @ua = UserAgent.find(params[:user_agent])
      @link = Link.new(params[:link].merge(:processed => false, :user_agent => @ua))
      if @link.save
        Resque.enqueue(LinkFetcher, @link.id)
        redirect_to link_path(@link)
      end    
    else
      flash[:error] = "You have exceeded the rate limit, please try again in a little bit"
      redirect_to root_path
    end
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  def index
    @links = Link.order('updated_at DESC').page(params[:page])
  end

  def show
    @link = Link.find(params[:id])
    @headers = @link.processed? ? YAML.load(@link.headers) : {}
  end

  def create
    unless RateLimiter.limit(request.remote_ip)
      @ua = UserAgent.find(params[:user_agent])
      @link = Link.new(params[:link].merge(:processed => false, :user_agent => @ua))
      if @link.save
        Resque.enqueue(LinkFetcher, @link.id)
        respond_to do |format|
          format.html { redirect_to links_path }
          format.js do
            @links = Link.order('updated_at DESC').page(params[:page])
            render :index
          end
        end
      end
    else
      flash[:error] = "You have exceeded the rate limit, please try again in a little bit"
      redirect_to root_path
    end
  end

  def raw
    @link = Link.find(params[:link_id])
    @headers = @link.processed ? YAML.load(@link.headers) : {}
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/link_helper.rb
module LinkHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fetchit</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class='container'>
  <div class='span-24 last'>
    <%= link_to content_tag('h1', "Fetchit", :class => ''), root_path(), :style => 'text-decoration: none;' %>
  </div>
  <%= yield %>
</div>

</body>
</html>

app/views/link/index.html.erb
<div class='span-24 last'>
	<div class='span-24 last'>
			Welcome <%= request.remote_ip %><br/>
			<%= RateLimiter.current(request.remote_ip) %> -> <%= RateLimiter.ttl(request.remote_ip) %><br/>
			<%= link_to "Resque Server", resque_server_path() %>
	</div>
  <div class='span-24 last' id='links'>
    <%= paginate @links %>
    <%= content_tag('h3', "Recent Links", :class => '') %>
    <table>
      <tr><th>URL</th><th>Created</th><th>Updated</th><th>Processed?</th><th>Error?</th></tr>
    <% @links.each do |link| %>
      <tr>
        <td><%= link_to link.url.truncate(50), link_path(link) %></td>
        <td><%= distance_of_time_in_words(link.created_at, Time.now) %> ago</td>
        <td><%= distance_of_time_in_words(link.updated_at, Time.now) %> ago</td>
        <td><%= link.processed? ? 'Yes' : 'No' %></td>
        <td><%= link.error.nil? ? 'No' : 'Yes' %></td>
      </td>
    <% end %>
    </table>
  </div>
  
  <%= form_for :link, :url => {:controller => 'link'} do |f| %>
    <p>
      <%= f.label :url, "Url" %><br/>
      <%= f.text_field :url %>
    </p>
    <p>
      <%= f.label :user_agent, "User Agent" %><br/>
      <%= select_tag "user_agent", options_from_collection_for_select(UserAgent.all, "id", "name")%>
    </p>
    <p>
      <%= f.submit "Submit", :disable_with => 'Submiting...' %>
    </p>
  <% end -%>
</div>

app/views/links/_link.html.erb
<tr>
  <td><%= link_to link.url.truncate(50), link %></td>
  <td><%= distance_of_time_in_words(link.created_at, Time.now) %> ago</td>
  <td><%= distance_of_time_in_words(link.updated_at, Time.now) %> ago</td>
  <td><%= link.processed? ? 'Yes' : 'No' %></td>
  <td><%= link.error.nil? ? 'No' : 'Yes' %></td>
</tr>

app/views/links/_links.html.erb
<%= content_tag('h3', "Recent Links", :class => '') %>
<div id='paginator'>
	<%= paginate @links, :remote => true %>
</div>

<table>
	<thead>
  	<tr><th>URL</th><th>Created</th><th>Updated</th><th>Processed?</th><th>Error?</th></tr>
	</thead>
	<tbody id="link_table">
		<%= render @links %>
	</tbody>
</table>

app/views/links/index.html.erb
<div class='span-24 last'>
	<div class='span-24 last'>
		<% if ENV['RAILS_ENV'] == 'development' %>
			Welcome <%= request.remote_ip %><br/>
			<%= RateLimiter.current(request.remote_ip) %> -> <%= RateLimiter.ttl(request.remote_ip) %><br/>
			<%= link_to "Resque Server", resque_server_path() %>
		<% end %>
	</div>
  <div class='span-24 last' id='links'>
		<%= render :partial => "links" %>
  </div>
  
  <%= form_for :link, :html => {:id => 'link_form'}, :remote => true do |f| %>
    <p>
      <%= f.label :url, "Url" %><br/>
      <%= f.text_field :url %>
    </p>
    <p>
      <%= f.label :user_agent, "User Agent" %><br/>
      <%= select_tag "user_agent", options_from_collection_for_select(UserAgent.all, "id", "name")%>
    </p>
    <p>
      <%= f.submit "Submit", :disable_with => 'Submiting...' %>
    </p>
  <% end -%>
</div>

app/views/links/index.js.erb
$('#link_table').html('<%= escape_javascript render(@links) %>');
$('#paginator').html('<%= escape_javascript (paginate(@links, :remote => true).to_s) %>');
$('#link_form').clearForm();

app/views/links/raw.html.erb
<div class='span-24 last'>
  <%= content_tag('h3', @link.url.truncate(50), :class => '') %>
  <%= content_tag('small', @link.url, :class => '') if @link.url.size > 50 %>
  <br/>
  <hr/>
  <div class='span-24 last'>
		<%= content_tag('h4', "User Agent", :class => '') %>
    <%= @link.user_agent.name%>: <%= @link.user_agent.description %>
  </div>
  <br/>
  <hr/>
  <div class='span-24 last'>
    <% if @link.error %>
      <%= content_tag('h4', "Errors", :class => '') %>
      <%= @link.error %>
    <% end %>
  </div>
  <br/>
  <hr/>
  <div class='span-24 last page_content'>
		<%= content_tag('h4', "Page Headers", :class => '') %>
		<table>
			<thead>
				<tr><th>Header</th><th>Value</th></tr>
			</thead>
			<tbody>
				<% @headers.each do |header, value| %>
					<tr><td><%= content_tag('b', header, :class => '') %></td>
						<td><%= value %></td></tr>
				<% end %>
			</tbody>
		</table>
  </div>
  <br/>
  <hr/>
	<%= content_tag('h4', "Page Content", :class => '') %>
	<%= link_to "Colorized body", link_path(@link) %><br/>
  <div class='span-24 last page_content'>
    <%= @link.body %>
  </div>
</div>

app/views/links/show.html.erb
<div class='span-24 last'>
  <%= content_tag('h3', @link.url.truncate(50), :class => '') %>
  <%= content_tag('small', @link.url, :class => '') if @link.url.size > 50 %>
  <br/>
  <hr/>
  <div class='span-24 last'>
		<%= content_tag('h4', "User Agent", :class => '') %>
    <%= @link.user_agent.name%>: <%= @link.user_agent.description %>
  </div>
  <br/>
  <hr/>
  <div class='span-24 last'>
    <% if @link.error %>
      <%= content_tag('h4', "Errors", :class => '') %>
      <%= @link.error %>
    <% end %>
  </div>
  <br/>
  <hr/>
  <div class='span-24 last page_content'>
		<%= content_tag('h4', "Page Headers", :class => '') %>
		<table>
			<thead>
				<tr><th>Header</th><th>Value</th></tr>
			</thead>
			<tbody>
				<% @headers.each do |header, value| %>
					<tr><td><%= content_tag('b', header, :class => '') %></td>
						<td><%= value %></td></tr>
				<% end %>
			</tbody>
		</table>
  </div>
  <br/>
  <hr/>
	<%= content_tag('h4', "Page Content", :class => '') %>
  <div class='span-24 last page_content'>
    <%= raw(@link.color) %>
  </div>
</div>